cf_elbo_type: -1
dec_filters: 128,64,32,24,16
decoder_cov_rank: 10
decoder_type: fixed_var
downsample: 3
enc_filters: 16,24,32,64,128
experiment: SVIExperiment
l2: 0.0
latent_dim: 100
logstd_init: -5
lr: 0.0001
model: ConditionalVISEM
num_convolutions: 3
num_sample_particles: 32
num_svi_particles: 4
pgm_lr: 0.005
preprocessing: realnvp
sample_img_interval: 10
test_batch_size: 64
train_batch_size: 256
use_amsgrad: false
use_cf_guide: false
use_upconv: false
validate: false
